### ISSUE TITLE
Issue with uniqueness constraint check

### ISSUE THREAD

**Issue by mohankumaru** [GordonSo/scimschema#24] opened 2020-09-12 10:34 UTC
Hi @GordonSo ,

I am writing a patch request validator and i encountered this issue,

The model has a multivalued complex attribute "operations",
Example,   
```
"Operations": [{
       "op":"add",
       "value":{
         "emails":[
         {
      "primary": True,
      "type": "work",
      "value": "mk@nl.com"
    }
    ],
    "active":False
       }
     }]
```
obviously , this value will go to "MultiValuedAttribute" class's "_validate" method.
But i get ```TypeError: unhashable type: 'dict'``` error for this array ```[{'op': 'add', 'value': {'emails': [{'primary': True, 'type': 'work', 'value': 'mk@nl.com'}], 'active': False}}]```.  Somewhere here ```for item, count in collections.Counter(list_values).items()```
The object inside array is valid.  
What do you think the issue is?

**Comment by GordonSo** [comment] 2020-09-13 05:40
Thanks for the interesting problem, and the example `Json`. 

I can reproduce that with 
```
import collections
collections.Counter([{"primary": True, "type": "work", "value": "mk@nl.com"}])
```
On the uniqueness validation, it uses the built-in Counter class to hash items in the array and ensure it only occurred once. 
The reason the above failed is that a dictionary is not hashable. However, I *think* the code had already cater for that: 
see here: https://github.com/GordonSo/scimschema/blob/master/src/scimschema/_model/attribute.py#L540-L544
It uses '_get_significant_value()' of items, so if the item is a dictionary, e.g. a `Complex' object, it should be validating only the uniqueness of the 'value' attribute; as per: https://github.com/GordonSo/scimschema/blob/master/src/scimschema/_model/attribute.py#L393-L399

As such, I should imagine the schema should be validated against the following instead:
```
collections.Counter(["mk@nl.com"])
```

Can you please check the schema is declaring a list of complex, not strings; otherwise provide the example schema you are using to validate against so I can better reproduce the problem?

**Comment by GordonSo** [comment] 2020-12-07 19:33
Going to close this issue due to its age and lack of reproduction step;

However, a reproduction example would still be appreciated, as we could potentially use it to provide a better error exception feedback. Thanks!

**Closed as completed by GordonSo** 2020-12-07 19:33 UTC
